/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/state': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * State
		 * @description Всё, что нужно для первой отрисовки: агенты, пространства, сводка, баланс.
		 */
		get: operations['state_api_state_get']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/events': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Events */
		get: operations['events_api_events_get']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/stats': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Statistics
		 * @description Полная статистика: итог, проекты × модели × роли, расход по дням.
		 *
		 *     `project` пустой — сводка по всем пространствам; иначе только по одному.
		 */
		get: operations['statistics_api_stats_get']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/call/{call_id}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Call Detail
		 * @description Что именно ушло в модель и что она ответила — по одному вызову.
		 */
		get: operations['call_detail_api_call__call_id__get']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/prompt': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Save Prompt
		 * @description Сохранить промпт агента. Перезапуск MCP-сервера не нужен — он читает файл заново.
		 */
		post: operations['save_prompt_api_prompt_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/role': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Role Save
		 * @description Создать агента или изменить его настройки (и промпт, если он прислан).
		 */
		post: operations['role_save_api_role_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/role/{name}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post?: never
		/**
		 * Role Delete
		 * @description Убрать агента. Промпт остаётся в roles/ — роль можно вернуть без потерь.
		 */
		delete: operations['role_delete_api_role__name__delete']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/project': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Project Save
		 * @description Создать рабочее пространство или переименовать существующее.
		 */
		post: operations['project_save_api_project_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/project/{pid}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post?: never
		/**
		 * Project Delete
		 * @description Убрать пространство из списка. Заметки остаются на диске — их можно вернуть.
		 */
		delete: operations['project_delete_api_project__pid__delete']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/run': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Run
		 * @description Запустить задачу на агенте прямо из интерфейса.
		 */
		post: operations['run_api_run_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/council': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/** Council */
		post: operations['council_api_council_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/context/{project}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Ctx List */
		get: operations['ctx_list_api_context__project__get']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/context': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/** Ctx Save */
		post: operations['ctx_save_api_context_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/upload': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Upload
		 * @description Принять материал и вернуть черновик заметки для контекста проекта.
		 *
		 *     Разбирает бесплатная роль: картинку — зрячий агент, текст — condenser.
		 *     В контекст черновик попадает не сам, а когда его сохранят: материал стоит
		 *     прочитать глазами прежде, чем он уедет в промпт каждого агента.
		 */
		post: operations['upload_api_upload_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/provider': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Provider Save
		 * @description Завести или изменить провайдера моделей (OpenAI-совместимый, Yandex, GigaChat).
		 */
		post: operations['provider_save_api_provider_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/provider/{name}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post?: never
		/** Provider Delete */
		delete: operations['provider_delete_api_provider__name__delete']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/model': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Model Save
		 * @description Завести или изменить модель. id — то, что уходит в поле model запроса.
		 */
		post: operations['model_save_api_model_post']
		/**
		 * Model Delete
		 * @description Идентификатор моделью приходит query-параметром: у Yandex он вида gpt://…/latest.
		 */
		delete: operations['model_delete_api_model_delete']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/provider/{name}/check': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Provider Check
		 * @description Проверить связь с провайдером. Без модели — запрос каталога, с моделью — короткий вызов.
		 */
		post: operations['provider_check_api_provider__name__check_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/intake/text': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Intake Text
		 * @description Разобрать вставленный кусок (лог, код, переписку) в черновик заметки.
		 */
		post: operations['intake_text_api_intake_text_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/workspace/rules': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Workspace Rules
		 * @description Забрать правила проекта из его репозитория в черновик _rules.md.
		 */
		post: operations['workspace_rules_api_workspace_rules_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
}
export type webhooks = Record<string, never>
export interface components {
	schemas: {
		/** Body_upload_api_upload_post */
		Body_upload_api_upload_post: {
			/** Project */
			project: string
			/**
			 * Question
			 * @default
			 */
			question: string
			/**
			 * File
			 * Format: binary
			 */
			file: string
		}
		/**
		 * CallOut
		 * @description Разговор целиком: что ушло в модель и что она ответила.
		 */
		CallOut: {
			/** Id */
			id: string
			/** Ts */
			ts: number
			/**
			 * Role
			 * @default
			 */
			role: string
			/**
			 * Model
			 * @default
			 */
			model: string
			/**
			 * Requested
			 * @default
			 */
			requested: string
			/**
			 * Project
			 * @default
			 */
			project: string
			/**
			 * Task
			 * @default
			 */
			task: string
			/**
			 * Messages
			 * @default []
			 */
			messages: components['schemas']['MessageOut'][]
			/**
			 * Text
			 * @default
			 */
			text: string
			/**
			 * Reasoning
			 * @default
			 */
			reasoning: string
			/**
			 * Tokens In
			 * @default 0
			 */
			tokens_in: number
			/**
			 * Tokens Out
			 * @default 0
			 */
			tokens_out: number
			/**
			 * Tokens Cached
			 * @default 0
			 */
			tokens_cached: number
			/**
			 * Tokens Reasoning
			 * @default 0
			 */
			tokens_reasoning: number
			/**
			 * Cost
			 * @default 0
			 */
			cost: number
			/**
			 * Seconds
			 * @default 0
			 */
			seconds: number
		}
		/**
		 * CheckOut
		 * @description Результат проверки связи с провайдером.
		 */
		CheckOut: {
			/** Ok */
			ok: boolean
			/**
			 * Status
			 * @default 0
			 */
			status: number
			/**
			 * Message
			 * @default
			 */
			message: string
			/**
			 * Detail
			 * @default
			 */
			detail: string
			/**
			 * Seconds
			 * @default 0
			 */
			seconds: number
			/**
			 * Model
			 * @default
			 */
			model: string
		}
		/**
		 * ClaudeSlot
		 * @description Расход Claude Code. Без стоимости: работа идёт по подписке.
		 */
		ClaudeSlot: {
			/**
			 * Calls
			 * @default 0
			 */
			calls: number
			/**
			 * Tokens In
			 * @default 0
			 */
			tokens_in: number
			/**
			 * Tokens Out
			 * @default 0
			 */
			tokens_out: number
			/**
			 * Tokens Cached
			 * @default 0
			 */
			tokens_cached: number
			/**
			 * Tokens Reasoning
			 * @default 0
			 */
			tokens_reasoning: number
		}
		/** ClaudeStat */
		ClaudeStat: {
			total: components['schemas']['ClaudeSlot']
			/** Daily */
			daily: {
				[key: string]: components['schemas']['ClaudeSlot']
			}
			/** Models */
			models: {
				[key: string]: components['schemas']['ClaudeSlot']
			}
			/** Projects */
			projects: {
				[key: string]: components['schemas']['ClaudeSlot']
			}
			/**
			 * Available
			 * @default false
			 */
			available: boolean
		}
		/**
		 * ContextOut
		 * @description Контекст проекта: список заметок и их содержимое.
		 */
		ContextOut: {
			/** Project */
			project: string
			/** Description */
			description: string
			/** Files */
			files: components['schemas']['NoteInfo'][]
			/** Core Chars */
			core_chars: number
			/** Notes */
			notes: {
				[key: string]: string
			}
		}
		/** CouncilOut */
		CouncilOut: {
			/** Topic */
			topic: string
			/** Transcript */
			transcript: components['schemas']['Turn'][]
			/** Cost */
			cost: number
		}
		/** DayStat */
		DayStat: {
			/**
			 * Calls
			 * @default 0
			 */
			calls: number
			/**
			 * Cost
			 * @default 0
			 */
			cost: number
			/**
			 * Tokens In
			 * @default 0
			 */
			tokens_in: number
			/**
			 * Tokens Out
			 * @default 0
			 */
			tokens_out: number
			/**
			 * Tokens Cached
			 * @default 0
			 */
			tokens_cached: number
			/**
			 * Tokens Reasoning
			 * @default 0
			 */
			tokens_reasoning: number
			/**
			 * Seconds
			 * @default 0
			 */
			seconds: number
			/**
			 * Errors
			 * @default 0
			 */
			errors: number
			/** Date */
			date: string
		}
		/**
		 * EventOut
		 * @description Строка журнала. Поля зависят от типа события, поэтому почти все необязательные.
		 */
		EventOut: {
			/** Ts */
			ts: number
			/** Event */
			event: string
			/** Id */
			id?: string | null
			/** Role */
			role?: string | null
			/** Model */
			model?: string | null
			/** Project */
			project?: string | null
			/** Task */
			task?: string | null
			/** Name */
			name?: string | null
			/** Topic */
			topic?: string | null
			/** Query */
			query?: string | null
			/** Kind */
			kind?: string | null
			/** Error */
			error?: string | null
			/** Tokens In */
			tokens_in?: number | null
			/** Tokens Out */
			tokens_out?: number | null
			/** Tokens Cached */
			tokens_cached?: number | null
			/** Tokens Reasoning */
			tokens_reasoning?: number | null
			/** Cost */
			cost?: number | null
			/** Seconds */
			seconds?: number | null
		}
		/** EventsOut */
		EventsOut: {
			/** Events */
			events: components['schemas']['EventOut'][]
			totals: components['schemas']['Totals']
		}
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components['schemas']['ValidationError'][]
		}
		/**
		 * MessageOut
		 * @description Сообщение промпта. content — строка либо части мультимодального сообщения.
		 */
		MessageOut: {
			/** Role */
			role?: string | null
			/** Content */
			content?:
				| string
				| {
						[key: string]: unknown
				  }[]
				| null
		}
		/** ModelIn */
		ModelIn: {
			/** Id */
			id: string
			/** Provider */
			provider: string
			/**
			 * Title
			 * @default
			 */
			title: string
			/**
			 * Price In
			 * @default 0
			 */
			price_in: number
			/**
			 * Price In Cached
			 * @default 0
			 */
			price_in_cached: number
			/**
			 * Price Out
			 * @default 0
			 */
			price_out: number
			/**
			 * Concurrency
			 * @default 3
			 */
			concurrency: number
			/**
			 * Vision
			 * @default false
			 */
			vision: boolean
		}
		/** ModelOut */
		ModelOut: {
			/**
			 * Id
			 * @default
			 */
			id: string
			/**
			 * Title
			 * @default
			 */
			title: string
			/** Provider */
			provider: string
			/**
			 * Price In
			 * @default 0
			 */
			price_in: number
			/**
			 * Price In Cached
			 * @default 0
			 */
			price_in_cached: number
			/**
			 * Price Out
			 * @default 0
			 */
			price_out: number
			/**
			 * Concurrency
			 * @default 3
			 */
			concurrency: number
			/**
			 * Vision
			 * @default false
			 */
			vision: boolean
		}
		/** ModelStat */
		ModelStat: {
			/**
			 * Calls
			 * @default 0
			 */
			calls: number
			/**
			 * Cost
			 * @default 0
			 */
			cost: number
			/**
			 * Tokens In
			 * @default 0
			 */
			tokens_in: number
			/**
			 * Tokens Out
			 * @default 0
			 */
			tokens_out: number
			/**
			 * Tokens Cached
			 * @default 0
			 */
			tokens_cached: number
			/**
			 * Tokens Reasoning
			 * @default 0
			 */
			tokens_reasoning: number
			/**
			 * Seconds
			 * @default 0
			 */
			seconds: number
			/**
			 * Errors
			 * @default 0
			 */
			errors: number
			/**
			 * By Project
			 * @default {}
			 */
			by_project: {
				[key: string]: components['schemas']['Slot']
			}
			/**
			 * By Role
			 * @default {}
			 */
			by_role: {
				[key: string]: components['schemas']['Slot']
			}
		}
		/** NoteIn */
		NoteIn: {
			/** Project */
			project: string
			/** Name */
			name: string
			/** Text */
			text: string
		}
		/** NoteInfo */
		NoteInfo: {
			/** Name */
			name: string
			/** Chars */
			chars: number
		}
		/** ProjectIn */
		ProjectIn: {
			/** Id */
			id: string
			/**
			 * Title
			 * @default
			 */
			title: string
		}
		/** ProjectOut */
		ProjectOut: {
			/** Id */
			id: string
			/** Title */
			title: string
		}
		/** ProjectStat */
		ProjectStat: {
			/**
			 * Calls
			 * @default 0
			 */
			calls: number
			/**
			 * Cost
			 * @default 0
			 */
			cost: number
			/**
			 * Tokens In
			 * @default 0
			 */
			tokens_in: number
			/**
			 * Tokens Out
			 * @default 0
			 */
			tokens_out: number
			/**
			 * Tokens Cached
			 * @default 0
			 */
			tokens_cached: number
			/**
			 * Tokens Reasoning
			 * @default 0
			 */
			tokens_reasoning: number
			/**
			 * Seconds
			 * @default 0
			 */
			seconds: number
			/**
			 * Errors
			 * @default 0
			 */
			errors: number
			/**
			 * By Model
			 * @default {}
			 */
			by_model: {
				[key: string]: components['schemas']['Slot']
			}
			/**
			 * By Role
			 * @default {}
			 */
			by_role: {
				[key: string]: components['schemas']['Slot']
			}
		}
		/** PromptIn */
		PromptIn: {
			/** Role */
			role: string
			/** Prompt */
			prompt: string
		}
		/**
		 * ProviderIn
		 * @description Провайдер из формы. Ключ приходит отдельным полем и в team.json не попадает.
		 */
		ProviderIn: {
			/** Name */
			name: string
			/**
			 * Title
			 * @default
			 */
			title: string
			/** Base Url */
			base_url: string
			/**
			 * Auth
			 * @default bearer
			 */
			auth: string
			/**
			 * Key Env
			 * @default
			 */
			key_env: string
			/**
			 * Verify Ssl
			 * @default true
			 */
			verify_ssl: boolean
			/**
			 * Send Thinking
			 * @default false
			 */
			send_thinking: boolean
			/** Api Key */
			api_key?: string | null
		}
		/**
		 * ProviderOut
		 * @description Провайдер моделей. Ключ наружу не отдаётся — только признак «задан».
		 */
		ProviderOut: {
			/** Name */
			name: string
			/** Title */
			title: string
			/** Base Url */
			base_url: string
			/** Auth */
			auth: string
			/**
			 * Key Env
			 * @default
			 */
			key_env: string
			/**
			 * Verify Ssl
			 * @default true
			 */
			verify_ssl: boolean
			/**
			 * Send Thinking
			 * @default true
			 */
			send_thinking: boolean
			/**
			 * Builtin
			 * @default false
			 */
			builtin: boolean
			/**
			 * Has Key
			 * @default false
			 */
			has_key: boolean
		}
		/**
		 * RoleIn
		 * @description Настройки агента из формы. prompt=None означает «промпт не трогать».
		 */
		RoleIn: {
			/** Name */
			name: string
			/**
			 * Model
			 * @default
			 */
			model: string
			/**
			 * Description
			 * @default
			 */
			description: string
			/** Fallback */
			fallback?: string | null
			/**
			 * Thinking
			 * @default false
			 */
			thinking: boolean
			/**
			 * Max Tokens
			 * @default 6000
			 */
			max_tokens: number
			/**
			 * Temperature
			 * @default 0.3
			 */
			temperature: number
			/** Prompt */
			prompt?: string | null
		}
		/**
		 * RoleOut
		 * @description Агент: настройки плюс текущий промпт.
		 */
		RoleOut: {
			/** Name */
			name: string
			/** Model */
			model: string
			/** Fallback */
			fallback?: string | null
			/**
			 * Thinking
			 * @default false
			 */
			thinking: boolean
			/**
			 * Max Tokens
			 * @default 4000
			 */
			max_tokens: number
			/**
			 * Temperature
			 * @default 0.3
			 */
			temperature: number
			/**
			 * Description
			 * @default
			 */
			description: string
			/**
			 * Prompt
			 * @default
			 */
			prompt: string
		}
		/** RoleStat */
		RoleStat: {
			/**
			 * Calls
			 * @default 0
			 */
			calls: number
			/**
			 * Cost
			 * @default 0
			 */
			cost: number
			/**
			 * Tokens In
			 * @default 0
			 */
			tokens_in: number
			/**
			 * Tokens Out
			 * @default 0
			 */
			tokens_out: number
			/**
			 * Tokens Cached
			 * @default 0
			 */
			tokens_cached: number
			/**
			 * Tokens Reasoning
			 * @default 0
			 */
			tokens_reasoning: number
			/**
			 * Seconds
			 * @default 0
			 */
			seconds: number
			/**
			 * Errors
			 * @default 0
			 */
			errors: number
			/**
			 * By Model
			 * @default {}
			 */
			by_model: {
				[key: string]: components['schemas']['Slot']
			}
		}
		/** RulesIn */
		RulesIn: {
			/** Project */
			project: string
			/** Repo */
			repo: string
			/**
			 * Compress
			 * @default true
			 */
			compress: boolean
		}
		/** RunOut */
		RunOut: {
			/** Text */
			text: string
			/** Model */
			model: string
			/** Cost */
			cost: number
			/** Seconds */
			seconds: number
			/** Tokens In */
			tokens_in: number
			/** Tokens Out */
			tokens_out: number
			/** Reasoning */
			reasoning: number
		}
		/** SavedOut */
		SavedOut: {
			/**
			 * Ok
			 * @default true
			 */
			ok: boolean
			/** Id */
			id?: string | null
			/** Title */
			title?: string | null
			/** Name */
			name?: string | null
			/** Chars */
			chars?: number | null
			/** File */
			file?: string | null
		}
		/**
		 * Slot
		 * @description Срез расхода: сколько вызовов, токенов и денег ушло в этом разрезе.
		 */
		Slot: {
			/**
			 * Calls
			 * @default 0
			 */
			calls: number
			/**
			 * Cost
			 * @default 0
			 */
			cost: number
			/**
			 * Tokens In
			 * @default 0
			 */
			tokens_in: number
			/**
			 * Tokens Out
			 * @default 0
			 */
			tokens_out: number
			/**
			 * Tokens Cached
			 * @default 0
			 */
			tokens_cached: number
			/**
			 * Tokens Reasoning
			 * @default 0
			 */
			tokens_reasoning: number
			/**
			 * Seconds
			 * @default 0
			 */
			seconds: number
			/**
			 * Errors
			 * @default 0
			 */
			errors: number
		}
		/** StateOut */
		StateOut: {
			/** Roles */
			roles: components['schemas']['RoleOut'][]
			/** Projects */
			projects: components['schemas']['ProjectOut'][]
			/** Models */
			models: {
				[key: string]: components['schemas']['ModelOut']
			}
			/** Providers */
			providers: components['schemas']['ProviderOut'][]
			totals: components['schemas']['Totals']
			/** Balance */
			balance?: number | null
		}
		/** StatsOut */
		StatsOut: {
			total: components['schemas']['Slot']
			total_24h: components['schemas']['Slot']
			/** Projects */
			projects: {
				[key: string]: components['schemas']['ProjectStat']
			}
			/** Models */
			models: {
				[key: string]: components['schemas']['ModelStat']
			}
			/** Roles */
			roles: {
				[key: string]: components['schemas']['RoleStat']
			}
			/** Daily */
			daily: components['schemas']['DayStat'][]
			claude: components['schemas']['ClaudeStat']
		}
		/** TaskIn */
		TaskIn: {
			/** Role */
			role: string
			/** Task */
			task: string
			/**
			 * Project
			 * @default
			 */
			project: string
			/**
			 * Extra
			 * @default
			 */
			extra: string
		}
		/** TextIn */
		TextIn: {
			/** Project */
			project: string
			/** Text */
			text: string
			/**
			 * Question
			 * @default
			 */
			question: string
			/**
			 * Source
			 * @default
			 */
			source: string
		}
		/**
		 * Totals
		 * @description Сводка из журнала — то, что висит в шапке.
		 */
		Totals: {
			/**
			 * Calls
			 * @default 0
			 */
			calls: number
			/**
			 * Cost
			 * @default 0
			 */
			cost: number
			/**
			 * Tokens In
			 * @default 0
			 */
			tokens_in: number
			/**
			 * Tokens Out
			 * @default 0
			 */
			tokens_out: number
			/**
			 * Calls 24H
			 * @default 0
			 */
			calls_24h: number
			/**
			 * Cost 24H
			 * @default 0
			 */
			cost_24h: number
			/**
			 * Errors
			 * @default 0
			 */
			errors: number
			/**
			 * By Model
			 * @default {}
			 */
			by_model: {
				[key: string]: {
					[key: string]: unknown
				}
			}
			/**
			 * By Role
			 * @default {}
			 */
			by_role: {
				[key: string]: {
					[key: string]: unknown
				}
			}
			/**
			 * By Project
			 * @default {}
			 */
			by_project: {
				[key: string]: {
					[key: string]: unknown
				}
			}
		}
		/** Turn */
		Turn: {
			/** Speaker */
			speaker: string
			/** Model */
			model: string
			/** Text */
			text: string
		}
		/** UploadOut */
		UploadOut: {
			/** Kind */
			kind: string
			/** Note */
			note: string
			/** Model */
			model: string
			/** Cost */
			cost: number
			/** Source */
			source: string
			/** Name */
			name: string
			/** Stored */
			stored: string
			/** Bytes */
			bytes: number
		}
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[]
			/** Message */
			msg: string
			/** Error Type */
			type: string
		}
	}
	responses: never
	parameters: never
	requestBodies: never
	headers: never
	pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
	state_api_state_get: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['StateOut']
				}
			}
		}
	}
	events_api_events_get: {
		parameters: {
			query?: {
				since?: number
				limit?: number
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['EventsOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	statistics_api_stats_get: {
		parameters: {
			query?: {
				days?: number
				project?: string
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['StatsOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	call_detail_api_call__call_id__get: {
		parameters: {
			query?: never
			header?: never
			path: {
				call_id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['CallOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	save_prompt_api_prompt_post: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['PromptIn']
			}
		}
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['SavedOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	role_save_api_role_post: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['RoleIn']
			}
		}
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['SavedOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	role_delete_api_role__name__delete: {
		parameters: {
			query?: never
			header?: never
			path: {
				name: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['SavedOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	project_save_api_project_post: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['ProjectIn']
			}
		}
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['SavedOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	project_delete_api_project__pid__delete: {
		parameters: {
			query?: never
			header?: never
			path: {
				pid: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['SavedOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	run_api_run_post: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['TaskIn']
			}
		}
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['RunOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	council_api_council_post: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['TaskIn']
			}
		}
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['CouncilOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	ctx_list_api_context__project__get: {
		parameters: {
			query?: never
			header?: never
			path: {
				project: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ContextOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	ctx_save_api_context_post: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['NoteIn']
			}
		}
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['SavedOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	upload_api_upload_post: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'multipart/form-data': components['schemas']['Body_upload_api_upload_post']
			}
		}
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['UploadOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	provider_save_api_provider_post: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['ProviderIn']
			}
		}
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['SavedOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	provider_delete_api_provider__name__delete: {
		parameters: {
			query?: never
			header?: never
			path: {
				name: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['SavedOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	model_save_api_model_post: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['ModelIn']
			}
		}
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['SavedOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	model_delete_api_model_delete: {
		parameters: {
			query: {
				id: string
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['SavedOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	provider_check_api_provider__name__check_post: {
		parameters: {
			query?: {
				model?: string
			}
			header?: never
			path: {
				name: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['CheckOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	intake_text_api_intake_text_post: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['TextIn']
			}
		}
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['UploadOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
	workspace_rules_api_workspace_rules_post: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['RulesIn']
			}
		}
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['UploadOut']
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HTTPValidationError']
				}
			}
		}
	}
}
